apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apdl

commonLabels:
  app.kubernetes.io/part-of: apdl

resources:
  - namespace.yaml
  - configmap.yaml
  - ingestion-deployment.yaml
  - config-deployment.yaml
  - query-deployment.yaml
  - agents-deployment.yaml
  - clickhouse-writer-deployment.yaml
  - ingress.yaml
